version: '3'
services:

  metabase:
    image: metabase/metabase:app-embedding
    environment:
      - MB_PREMIUM_EMBEDDING_TOKEN=${MB_PREMIUM_EMBEDDING_TOKEN}
      - MB_JWT_ENABLED=true
      - MB_JWT_IDENTITY_PROVIDER_URI=http://${HOST}:3001/api/auth/metabase
      - MB_JWT_SHARED_SECRET=ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
      - MB_DB_FILE=/data/metabase.db
    volumes:
      - metabase-data:/data
    ports:
      - "3000:3000"

  metalbase:
    build: .
    environment:
      - PORT=3001
      - METABASE_URL=http://${HOST}:3000
      - METABASE_JWT_SHARED_SECRET=ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ports:
      - "3001:3001"

volumes:
  metabase-data:
